/*
Strava API v3

Testing UploadsApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package stravaapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/stevenpelley/snowflake-strava/stravaapi"
)

func Test_stravaapi_UploadsApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test UploadsApiService CreateUpload", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.UploadsApi.CreateUpload(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UploadsApiService GetUploadById", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uploadId int64

		resp, httpRes, err := apiClient.UploadsApi.GetUploadById(context.Background(), uploadId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
