/*
Strava API v3

Testing AthletesApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package stravaapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/stevenpelley/snowflake-strava/stravaapi"
)

func Test_stravaapi_AthletesApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AthletesApiService GetLoggedInAthlete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.AthletesApi.GetLoggedInAthlete(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AthletesApiService GetLoggedInAthleteZones", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.AthletesApi.GetLoggedInAthleteZones(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AthletesApiService GetStats", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id int64

		resp, httpRes, err := apiClient.AthletesApi.GetStats(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AthletesApiService UpdateLoggedInAthlete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var weight float32

		resp, httpRes, err := apiClient.AthletesApi.UpdateLoggedInAthlete(context.Background(), weight).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
