/*
Strava API v3

The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stravaapi

import (
	"encoding/json"
)

// checks if the TemperatureStreamAllOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TemperatureStreamAllOf{}

// TemperatureStreamAllOf struct for TemperatureStreamAllOf
type TemperatureStreamAllOf struct {
	// The sequence of temperature values for this stream, in celsius degrees
	Data []int32 `json:"data,omitempty"`
}

// NewTemperatureStreamAllOf instantiates a new TemperatureStreamAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemperatureStreamAllOf() *TemperatureStreamAllOf {
	this := TemperatureStreamAllOf{}
	return &this
}

// NewTemperatureStreamAllOfWithDefaults instantiates a new TemperatureStreamAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemperatureStreamAllOfWithDefaults() *TemperatureStreamAllOf {
	this := TemperatureStreamAllOf{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *TemperatureStreamAllOf) GetData() []int32 {
	if o == nil || IsNil(o.Data) {
		var ret []int32
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemperatureStreamAllOf) GetDataOk() ([]int32, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *TemperatureStreamAllOf) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []int32 and assigns it to the Data field.
func (o *TemperatureStreamAllOf) SetData(v []int32) {
	o.Data = v
}

func (o TemperatureStreamAllOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TemperatureStreamAllOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableTemperatureStreamAllOf struct {
	value *TemperatureStreamAllOf
	isSet bool
}

func (v NullableTemperatureStreamAllOf) Get() *TemperatureStreamAllOf {
	return v.value
}

func (v *NullableTemperatureStreamAllOf) Set(val *TemperatureStreamAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableTemperatureStreamAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableTemperatureStreamAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemperatureStreamAllOf(val *TemperatureStreamAllOf) *NullableTemperatureStreamAllOf {
	return &NullableTemperatureStreamAllOf{value: val, isSet: true}
}

func (v NullableTemperatureStreamAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemperatureStreamAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


