/*
Strava API v3

The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stravaapi

import (
	"encoding/json"
)

// checks if the MovingStreamAllOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MovingStreamAllOf{}

// MovingStreamAllOf struct for MovingStreamAllOf
type MovingStreamAllOf struct {
	// The sequence of moving values for this stream, as boolean values
	Data []bool `json:"data,omitempty"`
}

// NewMovingStreamAllOf instantiates a new MovingStreamAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMovingStreamAllOf() *MovingStreamAllOf {
	this := MovingStreamAllOf{}
	return &this
}

// NewMovingStreamAllOfWithDefaults instantiates a new MovingStreamAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMovingStreamAllOfWithDefaults() *MovingStreamAllOf {
	this := MovingStreamAllOf{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *MovingStreamAllOf) GetData() []bool {
	if o == nil || IsNil(o.Data) {
		var ret []bool
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MovingStreamAllOf) GetDataOk() ([]bool, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *MovingStreamAllOf) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []bool and assigns it to the Data field.
func (o *MovingStreamAllOf) SetData(v []bool) {
	o.Data = v
}

func (o MovingStreamAllOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MovingStreamAllOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableMovingStreamAllOf struct {
	value *MovingStreamAllOf
	isSet bool
}

func (v NullableMovingStreamAllOf) Get() *MovingStreamAllOf {
	return v.value
}

func (v *NullableMovingStreamAllOf) Set(val *MovingStreamAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableMovingStreamAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableMovingStreamAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMovingStreamAllOf(val *MovingStreamAllOf) *NullableMovingStreamAllOf {
	return &NullableMovingStreamAllOf{value: val, isSet: true}
}

func (v NullableMovingStreamAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMovingStreamAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


