/*
Strava API v3

The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stravaapi

import (
	"encoding/json"
)

// checks if the TimedZoneRangeAllOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TimedZoneRangeAllOf{}

// TimedZoneRangeAllOf struct for TimedZoneRangeAllOf
type TimedZoneRangeAllOf struct {
	// The number of seconds spent in this zone
	Time *int32 `json:"time,omitempty"`
}

// NewTimedZoneRangeAllOf instantiates a new TimedZoneRangeAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTimedZoneRangeAllOf() *TimedZoneRangeAllOf {
	this := TimedZoneRangeAllOf{}
	return &this
}

// NewTimedZoneRangeAllOfWithDefaults instantiates a new TimedZoneRangeAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTimedZoneRangeAllOfWithDefaults() *TimedZoneRangeAllOf {
	this := TimedZoneRangeAllOf{}
	return &this
}

// GetTime returns the Time field value if set, zero value otherwise.
func (o *TimedZoneRangeAllOf) GetTime() int32 {
	if o == nil || IsNil(o.Time) {
		var ret int32
		return ret
	}
	return *o.Time
}

// GetTimeOk returns a tuple with the Time field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimedZoneRangeAllOf) GetTimeOk() (*int32, bool) {
	if o == nil || IsNil(o.Time) {
		return nil, false
	}
	return o.Time, true
}

// HasTime returns a boolean if a field has been set.
func (o *TimedZoneRangeAllOf) HasTime() bool {
	if o != nil && !IsNil(o.Time) {
		return true
	}

	return false
}

// SetTime gets a reference to the given int32 and assigns it to the Time field.
func (o *TimedZoneRangeAllOf) SetTime(v int32) {
	o.Time = &v
}

func (o TimedZoneRangeAllOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TimedZoneRangeAllOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Time) {
		toSerialize["time"] = o.Time
	}
	return toSerialize, nil
}

type NullableTimedZoneRangeAllOf struct {
	value *TimedZoneRangeAllOf
	isSet bool
}

func (v NullableTimedZoneRangeAllOf) Get() *TimedZoneRangeAllOf {
	return v.value
}

func (v *NullableTimedZoneRangeAllOf) Set(val *TimedZoneRangeAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableTimedZoneRangeAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableTimedZoneRangeAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTimedZoneRangeAllOf(val *TimedZoneRangeAllOf) *NullableTimedZoneRangeAllOf {
	return &NullableTimedZoneRangeAllOf{value: val, isSet: true}
}

func (v NullableTimedZoneRangeAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTimedZoneRangeAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


